### ISSUE TITLE
AMPlify predict results in a TypeError 

### ISSUE THREAD

**Issue by Legana** [bcgsc/AMPlify#1]
Hi, I tried to predict some sequences following your example in the README but unfortunately resulted in a "TypeError: add_weight() got multiple values for argument 'name'" When I googled the error, it looked to be related to Keras.

**My test file:**
test.fa : 
>teAMP0001
QLPICGETCVLGGCYTPNCRCQYPICVR

**My code**
`python AMPlify.py -md ../models/ -s ..test.fa` 

**Code results**

Loading models...
2021-02-10 11:04:31.889911: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-10 11:04:31.890619: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "AMPlify.py", line 242, in <module>
    main()
  File "AMPlify.py", line 179, in main
    out_model = load_multi_model(models, build_amplify)
  File "AMPlify.py", line 88, in load_multi_model
    model = architecture()
  File "AMPlify.py", line 59, in build_amplify
    hidden = Attention(name='Attention')(hidden)
  File "/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/AMPlify-1.0.0/src/layers.py", line 111, in build
    self.W = self.add_weight((amount_features, attention_size),
TypeError: add_weight() got multiple values for argument 'name'

**My `pip freeze` information**

absl-py==0.11.0
astunparse==1.6.3
biopython @ file:///opt/concourse/worker/volumes/live/cdcffdf0-9e67-4291-4fd7-8d3bf14bf437/volume/biopython_1600298878668/work
brotlipy==0.7.0
cachetools==4.2.1
certifi==2020.12.5
cffi @ file:///opt/concourse/worker/volumes/live/8fbed55e-0573-4246-7cf9-162067141d5e/volume/cffi_1605538070636/work
chardet @ file:///opt/concourse/worker/volumes/live/a5a7c56b-23cb-471d-7404-f4130b8aed33/volume/chardet_1605303184529/work
conda==4.9.2
conda-package-handling @ file:///opt/concourse/worker/volumes/live/a7e34989-4c54-4cb6-4156-4e58ee270730/volume/conda-package-handling_1603018121300/work
cryptography @ file:///opt/concourse/worker/volumes/live/62f9527a-361c-47e5-5709-227a4a523add/volume/cryptography_1605544472602/work
flatbuffers==1.12
gast==0.3.3
google-auth==1.25.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
Keras==2.4.3
Keras-Preprocessing==1.1.2
Markdown==3.3.3
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///opt/concourse/worker/volumes/live/5572694e-967a-4c0c-52cf-b53d43e72de9/volume/numpy_and_numpy_base_1603491881791/work
oauthlib==3.1.0
opt-einsum==3.3.0
pandas==1.2.1
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1605545627475/work
PySocks @ file:///opt/concourse/worker/volumes/live/85a5b906-0e08-41d9-6f59-084cee4e9492/volume/pysocks_1594394636991/work
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-oauthlib==1.3.0
rsa==4.7
ruamel-yaml==0.15.87
scipy==1.6.0
six @ file:///opt/concourse/worker/volumes/live/5b31cb27-1e37-4ca5-6e9f-86246eb206d2/volume/six_1605205320872/work
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
termcolor==1.1.0
tqdm @ file:///tmp/build/80754af9/tqdm_1605303662894/work
typing-extensions==3.7.4.3
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
Werkzeug==1.0.1
wrapt==1.12.1

**OS**

I run macOS (Big Sur) 11.2

**Comment by mark0428** [comment]
Hi @Legana. Thanks for reporting this. It seems that the problem is related to the version of keras you were using. The model was implemented with keras 2.2.4, but you were running it with keras 2.4.3. If you do not want to downgrade your keras, I have made some changes to adapt the code to higher versions of keras. You may just clone the repository (with my most recent updates), and that should work.

**Comment by Legana** [comment]
hi @mark0428 , it works now, thanks for your reply!
