### ISSUE TITLE
Add version info

### ISSUE THREAD

**Issue by jasmezz** [bcgsc/AMPlify#13]
For reproducibility and usage in pipelines with multiple tools, it would be useful to have AMPlify output its version number. Best would be to add a flag like:
```
$ AMPlify --version
AMPlify 1.0.3
```
Alternatively, just adding the version to the usage info or to the output of the help flag would be helpful, like this:
```
$ AMPlify --help
AMPlify 1.0.3
Using TensorFlow backend.
usage: AMPlify.py [-h] [-md MODEL_DIR]
                  [-m MODEL_NAME MODEL_NAME MODEL_NAME MODEL_NAME MODEL_NAME]
                  -s SEQS [-od OUT_DIR] [-of {txt,tsv}] [-att {on,off}]

AMPlify
------------------------------------------------------
Predict whether a sequence is AMP or not.
...
```

**Comment by mark0428** [comment]
Thanks for the helpful suggestion! We have now added the version number into the usage information.
