### ISSUE TITLE
Singularity container crashes for AMPlify 2.0.0

### ISSUE THREAD

**Issue by jasmezz** [bcgsc/AMPlify#16]
The new AMPlify version 2.0.0 runs successfully on docker and conda. However with singularity I get the exit code 1 and the error message:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/share/amplify/src/AMPlify.py", line 19, in <module>
    from layers import Attention, MultiHeadAttention
  File "/usr/local/share/amplify/src/layers.py", line 11, in <module>
    from keras import backend as K
  File "/usr/local/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 55, in <module>
    from tensorflow.python.platform import app
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 24, in <module>
    from tensorflow.python.platform import flags
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/usr/local/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

This is the executed command:
`AMPlify -s sample_1.faa`

The amino acid fasta file in this case is the annotated output from pyrodigal 3.3.0, but the described behaviour seems independent of the annotation tool. It is also reproducible with prokka and bakta.

Example input faa file: [sample_1.txt](https://github.com/bcgsc/AMPlify/files/14761002/sample_1.txt)
(The actual extension was `.faa`, I just changed it to `.txt` because otherwise GitHub wouldn't attach it.)

**Comment by lcoombe** [comment]
Hi @jasmezz,

Thanks for the report!

For your conda environment, when you run`AMPlify -h`, is it using tensorflow backend (like your showed for singularity) or theano?
Also, what version of tensorflow do you have installed? I suspect it could be to do with the tensorflow version, as that was one pin that changed in the latest conda recipe.

Thank you for your interest in AMPlify!
Lauren

**Comment by jasmezz** [comment]
Thanks for your fast reply, @lcoombe! :rocket:

To give some details for conda: It seems to depend on the theano/tensorflow versions which backend is being used.

### Standard conda installation

A simple `mamba create -n amplify amplify` installs the versions:

- amplify 2.0.0
- tensorflow 1.10.0
- theano 1.0.4

and uses the **theano backend**:

```
$ AMPlify -h
Using Theano backend.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
```

Here, AMPlify finishes successfully (running `AMPlify -s sample_1.faa`), just a few warnings show up like:

```
UserWarning: RNN dropout is no longer supported with the Theano backend due to technical limitations. You can either set `dropout` and `recurrent_dropout` to 0, or use the TensorFlow backend.
```

### Updated conda installation

Using the versions tensorflow 1.12.0 and theano 1.0.5, the **tensorflow backend** is used instead and no user warnings show up when running AMPlify.

```
$ AMPlify -h
Using TensorFlow backend.
usage: AMPlify.py [-h] [-m {balanced,imbalanced}] -s SEQS [-od OUT_DIR]
                  [-of {txt,tsv}] [-sub {on,off}] [-att {on,off}]

AMPlify v2.0.0
```

**Comment by lcoombe** [comment]
Hi @jasmezz,

Thank you for the information!

I'm glad at least you have a functional conda installation, but absolutely we want to have a functional docker image with singularity as well! We're looking into it on our side - ideally we'd do a fix on the conda recipe so that the generated docker image is functional in singularity.
We think it is due to the tensorflow version - we can't install 1.12.0 within the bioconda recipe, but that is the correct version to use. We're trying to figure out a workaround - I'll let you know what we come up with!

**Comment by lcoombe** [comment]
Hi @jasmezz,

So, we traced the issue in the conda recipe back to a version of the dependency `absl-py` and pinned it to a lower version (<2). Now, with the updated recipe, when I `conda install amplify`, I see it using TensorFlow as the back-end, as expected. I also found that the docker image is working on singularity as expected.

So, hopefully by using the updated conda recipe (or updated docker image), the error should be resolved!

Let me know if you have any other issues,
Lauren

**Comment by jasmezz** [comment]
Thank you so much for digging into this and fixing it so fast, @lcoombe! :rocket:

All containers + conda are working like a charm on our side as well. Thanks again, and I'll leave you the reference of our project if you are interested, what we use AMPlify for:
nf-core/funcscan ([website](https://nf-co.re/funcscan/1.1.5), [GitHub](https://github.com/nf-core/funcscan)) – a metagenome screening pipeline with antibiotic resistance prediction as one workflow.
